name: Build, Test and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore STIN_BurzaModule/STIN_BurzaModule.sln

      - name: Build solution
        run: dotnet build STIN_BurzaModule/STIN_BurzaModule.sln --configuration Release --no-restore

      - name: Install Coverlet (pro měření coverage)
        run: dotnet add STIN_BurzaModule.Tests/STIN_BurzaModule.Tests.csproj package coverlet.collector

      - name: Run tests with coverage
        run: |
          dotnet test STIN_BurzaModule.Tests/STIN_BurzaModule.Tests.csproj \
            --no-build \
            --no-restore \
            --verbosity normal \
            --collect:"XPlat Code Coverage" \
            
            
      - name: Upload coverage to Codecov (volitelné)
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Vyžaduje nastavení secret v GitHub repo
          files: ./**/coverage.cobertura.xml

      - name: Publish web project
        run: dotnet publish STIN_BurzaModule/STIN_BurzaModule.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'STINBurzaModule20250514183057'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
