name: Build, Test and Deploy to Azure

on:
  push:
    branches:
<<<<<<< HEAD
      - main
=======
      - added-pipeline
>>>>>>> bc7375c49748df7e9b107dbfded969395e0103c3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
<<<<<<< HEAD
        run: dotnet restore ./BurzaModule.sln

      - name: Build project
        run: dotnet build ./BurzaModule.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./BurzaModule.Tests/BurzaModule.Tests.csproj --no-build --verbosity normal

      - name: Publish project
        run: dotnet publish ./STIN_BurzaModule/STIN_BurzaModule.csproj --configuration Release --output ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'STINBurzaModule20250514183057'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
=======
        run: dotnet restore ./STIN_BurzaModule.sln

      - name: Build project
        run: dotnet build ./STIN_BurzaModule.sln --configuration Release --no-restore



>>>>>>> bc7375c49748df7e9b107dbfded969395e0103c3
