name: Build, Test and Deploy with Coverage

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install tools
        run: |
          dotnet restore STIN_BurzaModule/STIN_BurzaModule.sln
          dotnet add STIN_BurzaModule.Tests/STIN_BurzaModule.Tests.csproj package coverlet.collector
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Build
        run: dotnet build STIN_BurzaModule/STIN_BurzaModule.sln --configuration Release --no-restore

      - name: Run tests with coverage
        id: tests
        run: |
          mkdir -p TestResults
          dotnet test STIN_BurzaModule.Tests/STIN_BurzaModule.Tests.csproj \
            --no-build \
            --no-restore \
            --settings coverlet.runsettings \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults \
            --logger "console;verbosity=normal" \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Include="[STIN_BurzaModule*]*" \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[xunit.*]*;[*.Tests]*"

      - name: Verify coverage data
        run: |
          echo "### Coverage file content ###"
          COVERAGE_FILE=$(find ./TestResults -name "coverage.cobertura.xml" | head -1)
          head -n 20 "$COVERAGE_FILE"
          echo "### File size ###"
          ls -la "$COVERAGE_FILE"
          if [ ! -s "$COVERAGE_FILE" ]; then
            echo "::error::Coverage file is empty!"
            exit 1
          fi

      - name: Generate HTML report
        run: |
          reportgenerator \
            "-reports:$(find ./TestResults -name coverage.cobertura.xml | head -1)" \
            "-targetdir:coveragereport" \
            "-sourcedirs:$GITHUB_WORKSPACE/STIN_BurzaModule" \
            "-reporttypes:Html;Badges" \
            "-title:STIN Burza Module Coverage" \
            "-verbosity:Warning"

      - name: Verify report content
        run: |
          echo "### Report files ###"
          find ./coveragereport -type f
          echo "### Index.html content ###"
          grep -A 10 -B 10 "coverage summary" ./coveragereport/index.html || echo "No coverage data found!"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coveragereport/index.html
            coveragereport/**/*.html
            coveragereport/**/*.css
            coveragereport/**/*.js
            coveragereport/**/*.svg
          if-no-files-found: error
          retention-days: 5

      - name: Publish
        run: dotnet publish STIN_BurzaModule/STIN_BurzaModule.csproj --configuration Release --output ./publish
