name: Build, Test and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: |
          dotnet restore STIN_BurzaModule/STIN_BurzaModule.sln
          dotnet add STIN_BurzaModule.Tests/STIN_BurzaModule.Tests.csproj package coverlet.collector
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Build
        run: dotnet build STIN_BurzaModule/STIN_BurzaModule.sln --configuration Release --no-restore

      - name: Run tests with coverage
        id: tests
        run: |
          mkdir -p TestResults
          dotnet test STIN_BurzaModule.Tests/STIN_BurzaModule.Tests.csproj \
            --no-build \
            --no-restore \
            --logger "console;verbosity=normal" \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Include=\"[STIN_BurzaModule*]*\" \
            -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude=\"[xunit.*]*;[*.Tests]*\"

      - name: Find coverage file
        id: coverage
        run: |
          COVERAGE_FILE=$(find ./TestResults -name "coverage.cobertura.xml" | head -1)
          if [ -z "$COVERAGE_FILE" ]; then
            echo "::error::Coverage file not found!"
            exit 1
          fi
          echo "file=$COVERAGE_FILE" >> $GITHUB_OUTPUT
          echo "##[group]Coverage file content"
          head -n 20 "$COVERAGE_FILE"
          echo "##[endgroup]"

      - name: Generate HTML report
        run: |
          reportgenerator \
            "-reports:${{ steps.coverage.outputs.file }}" \
            "-targetdir:coveragereport" \
            "-reporttypes:Html" \
            "-sourcedirs:./STIN_BurzaModule" \
            "-verbosity:Warning"

      - name: Verify report
        run: |
          echo "##[group]Generated report files"
          ls -laR ./coveragereport
          echo "##[endgroup]"
          if [ ! -f "./coveragereport/index.html" ]; then
            echo "::error::HTML report was not generated!"
            exit 1
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport/
          if-no-files-found: error
          retention-days: 3

      - name: Publish and deploy
        if: success()
        run: |
          dotnet publish STIN_BurzaModule/STIN_BurzaModule.csproj --configuration Release --output ./publish
          # Zde pokračujte s deployem
