name: Build, Test and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: |
          dotnet restore STIN_BurzaModule/STIN_BurzaModule.sln
          dotnet add STIN_BurzaModule.Tests/STIN_BurzaModule.Tests.csproj package coverlet.collector
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Build
        run: dotnet build STIN_BurzaModule/STIN_BurzaModule.sln --configuration Release --no-restore

      - name: Run tests with coverage
        run: |
          mkdir -p TestResults
          dotnet test STIN_BurzaModule.Tests/STIN_BurzaModule.Tests.csproj \
            --no-build \
            --no-restore \
            --settings coverlet.runsettings \
            --collect:"XPlat Code Coverage" \
            --results-directory TestResults

      - name: Generate HTML report
        run: |
          COVERAGE_FILE=$(find ./TestResults -name "coverage.cobertura.xml" | head -1)
          reportgenerator \
            "-reports:$COVERAGE_FILE" \
            "-targetdir:coveragereport" \
            "-reporttypes:Html"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport/
          retention-days: 3

      - name: Publish and deploy
        run: |
          dotnet publish STIN_BurzaModule/STIN_BurzaModule.csproj --configuration Release --output ./publish
